[BCHDCC-50] Add Translation Bar with Flag Icons to Header
bchd/bahc-ohana-api pull request #324
Opened 2024-09-11 22:06 UTC by emmabjj

## Description

Add responsive, accessible translation bar with flag icons to header and hamburger menu. English, Arabic, Chinese Simplified, Chinese Traditional, French, Korean, and Spanish. Flag icon links correctly translate the page into the language chosen.

Followed this [figma design](https://www.figma.com/design/xli1XXrftaijx1KLldloK7/BCHD---CHARMcare%3A-Tailwind-Upgrade?node-id=2389-2504&t=UbP7xBuoeVwNMWtM-0)

## Motivation and Context

[BCHDCC-50](https://app.clickup.com/t/9006094761/BCHDCC-50) - Add a "Translate to" bar under the main header - full page layout 

This translation bar replaces the google translate widget in the non-admin site. 

## Screenshots

### Desktop (translation bar under header)
<img width="1001" alt="Screenshot 2024-09-11 at 5 00 02 PM" src="https://github.com/user-attachments/assets/e072f251-e2f1-41b1-a25d-b35b9500ecd0">

-------------------------

### iPad (in hamburger)
<img width="384" alt="Screenshot 2024-09-11 at 5 02 08 PM" src="https://github.com/user-attachments/assets/8ad480c0-7712-4b2f-bf44-c7acb3823e40">

-------------------------

### Mobile (in hamburger)
<img width="298" alt="Screenshot 2024-09-11 at 5 02 35 PM" src="https://github.com/user-attachments/assets/b77a8282-8b8b-45a3-9acd-b134512f444c">

-------------------------

### Language Translations
#### Arabic
<img width="1044" alt="Screenshot 2024-09-11 at 5 03 52 PM" src="https://github.com/user-attachments/assets/aec6f1d8-2355-4911-86ae-ab3ed559fe8d">

<img width="385" alt="Screenshot 2024-09-11 at 5 04 21 PM" src="https://github.com/user-attachments/assets/aadc0f02-659d-4c24-b72c-d7e036970e41">

<img width="359" alt="Screenshot 2024-09-11 at 5 04 58 PM" src="https://github.com/user-attachments/assets/4782c930-48e3-4083-8423-9dd93778f69b">

<img width="1023" alt="Screenshot 2024-09-11 at 5 05 47 PM" src="https://github.com/user-attachments/assets/ca556cb2-6e3f-41e7-8774-5fad593f027f">

**Libraries Added**
No libraries added

## Migrations to Run: Yes / **No**

## Tests to Run
All existing tests pass

## Internal Checklist

- [ ] My code follows the code style of this project (https://rubystyle.guide/).
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-09-12 14:12 UTC, anna-dorigo requested changes
This looks great on all the different browser sizes, and the menu looks clean and nice. There is just a small issue that I pointed put.

2024-09-12 14:12 UTC, anna-dorigo commented on app/views/shared/_header.html.haml
> +      var text = element.textContent || element.innerText;
While testing this locally I noticed that the placeholders are not translated: 
![image](https://github.com/user-attachments/assets/ea51cdbf-9320-4b8a-ab6a-f4495a07aea6)

![image](https://github.com/user-attachments/assets/0d22a017-971d-4640-9373-c853aedc7db8)

Maybe we need to add here a case to account for the placeholder before we sent the text to the API.

2024-09-12 14:31 UTC, emmabjj commented on app/views/shared/_header.html.haml
> +      var text = element.textContent || element.innerText;
@anna-dorigo Just added a case for the placeholder text in the js - thanks! 👏

2024-09-15 23:16 UTC, anna-dorigo approved these changes
👍

2024-09-16 13:34 UTC, merged