[BCHDCC-95] Hide footer links and List Your Service button
bchd/bahc-ohana-api pull request #341
Opened 2024-11-14 20:32 UTC by micaelacunhadev

## Description

Added 'hidden' class to the 'List Your Services' button and link in the header and to links in the footer to hide them from the page in both the desktop and mobile versions.

## Motivation and Context

[BCHDCC-95](https://app.clickup.com/t/9006094761/BCHDCC-##) - Hide footer links and List Your Service button

      
We want the List Your Services button and links in the footer hidden for now.

## Screenshots

 Desktop view - NOT signed in
<img width="1075" alt="Screenshot 2024-11-14 at 3 17 55 PM" src="https://github.com/user-attachments/assets/3dc50652-0320-4990-8f7f-c0175a49b222">
Desktop view - signed in
<img width="966" alt="Screenshot 2024-11-14 at 3 19 38 PM" src="https://github.com/user-attachments/assets/4b7e9ba2-aacc-4c54-8a4e-c720127cebee">

Mobile view - NOT signed in
<img width="710" alt="Screenshot 2024-11-14 at 3 18 22 PM" src="https://github.com/user-attachments/assets/ce523e00-4b7b-4d4e-a4f8-a77b159658f8">

Mobile view - signed in
<img width="710" alt="Screenshot 2024-11-14 at 3 19 14 PM" src="https://github.com/user-attachments/assets/a2612497-f40c-431d-a30c-df9dd657a0ff">

## Migrations to Run: No

## Tests to Run
None

## Internal Checklist

- [ ] My code follows the code style of this project (https://rubystyle.guide/).
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-11-15 14:00 UTC, anna-dorigo requested changes
Since we are leaving the items there (not deleting only hiding them) for future use, I think would be good to add a comment for future developers to know why there are there but hidden all the time.

2024-11-15 15:34 UTC, micaelacunhadev commented
> Since we are leaving the items there (not deleting only hiding them) for future use, I think would be good to add a comment for future developers to know why there are there but hidden all the time.

@anna-dorigo good point! I just added comments to where I added the `hidden` class.

2024-11-18 19:36 UTC, anna-dorigo commented on app/views/shared/_footer.html.haml
> +    -#  please remove this commment block when revisiting this
```suggestion
    -# please remove this comment block when revisiting this
```

2024-11-18 19:37 UTC, anna-dorigo commented on app/views/shared/_header.html.haml
> +      -#  please remove this commment block when revisiting this
```suggestion
      -# please remove this comment block when revisiting this
```

2024-11-18 19:38 UTC, anna-dorigo commented on app/views/shared/_header.html.haml
> +      -#  please remove this commment block when revisiting this
```suggestion
      -# please remove this comment block when revisiting this
```

2024-11-18 19:49 UTC, anna-dorigo approved these changes
This looks good! I just fixed a typo and an extra white space.

2024-11-18 20:56 UTC, merged