Feature/ahc 1014 local ruby env
bchd/bahc-ohana-api pull request #5
Opened 2019-02-25 17:49 UTC by mkantzerFearless

Confiogure local environment with docker?

2019-03-05 14:05 UTC, solipet requested changes

2019-03-15 14:24 UTC, mkantzerFearless commented on config/environments/docker-local.rb
> +Rails.application.configure do
I dont think this does mirror the development though, right?

2019-03-15 19:25 UTC, mkantzerFearless commented on config/database.yml
> +  url: <%= ENV['DATABASE_URL'] %>
I think that makes a lot of sense; dont set a default if it isnt used in multiple places / if everything is setting its own.

2019-03-15 19:26 UTC, mkantzerFearless commented on config/database.yml
> +  url: <%= ENV['DATABASE_URL'] %>
Although im a bit confused by dev/test taking `database` but prod taking a URL.

2019-03-29 13:09 UTC, solipet commented on config/database.yml
> +  url: <%= ENV['DATABASE_URL'] %>
We can set the component vars for all environments -- if you then set `DATABASE_URL` in your environment, that overrides the component vars.

2019-03-29 13:12 UTC, solipet commented on config/environments/docker-local.rb
> +Rails.application.configure do
Erm, I _thought_ I did a diff against development and it was the same, but just tried again and ... nope. ¯\_(ツ)_/¯

nevermind... ;-)

2019-03-29 13:27 UTC, mkantzerFearless commented
Dont Need

2019-03-29 13:27 UTC, closed without merging